services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - mongodb
    restart: on-failure
    command: node dist/main.js

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
